language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo add-apt-repository -y ppa:dns/gnu
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
    - sudo apt-get install cmake bison freeglut3-dev libglew-dev gcc-4.7 g++-4.7
    # Tests requirements
    - sudo apt-get install libcppunit-dev libxmu-dev libxi-dev valgrind
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
before_script:
    - mkdir build
    - cd build
    - cmake -DTESTS=ON ${CMAKE_ARGS} ..
script: make && valgrind --tool=memcheck --leak-check=full bin/glsl_tests ../mesa-glsl/tests/
env:
    - CMAKE_ARGS=""
    - CMAKE_ARGS="-DUSE_MESA=ON"
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
    irc:
        channels:
            - "chat.freenode.net#glsl-debugger"
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
    - linux
